# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Readit', '0007_auto_20180113_0933'),
        ('Readit', '0006_auto_20180113_1115'),
    ]

    operations = [
    ]
