# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Readit', '0008_merge_20180113_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Readit.Comment'),
        ),
    ]
