# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Readit', '0008_merge_20180113_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='admins',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
