# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Readit', '0009_auto_20180113_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
