# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Readit', '0011_remove_post_type'),
        ('Readit', '0010_remove_comment_comment'),
    ]

    operations = [
    ]
